Consistently Move notes about github to own section
quicwg/qlog pull request #327
Opened 2023-07-07 14:19 UTC by LPardue

- Editorialize main schema intro
- Move note about github to own section

2023-07-07 14:49 UTC, rmarx requested changes
The github-part here is fine, but the main schema intro editorializing could use some attention. Left notes on this text at https://github.com/quicwg/qlog/pull/326, so maybe best to close that PR, implement changes here?

2023-07-07 15:02 UTC, LPardue commented
oops, this was not supposed to include the editorial changes to main-schema, only quic and h3 docs. Removed the bad commit.

2023-07-08 19:37 UTC, marten-seemann approved these changes

2023-07-10 09:42 UTC, rmarx approved these changes

2023-07-10 09:43 UTC, merged