Create ALPNIdentifier type to allow bytes or string presentation
quicwg/qlog pull request #385
Opened 2024-01-28 19:53 UTC by LPardue

ALPN IDs aren't guaranteed to be safe text, so allow logging the byte
sequence. However, don't force endpoint to do that if their willing
to do some safety checking or safe encoding.

Closes #368

2024-01-29 10:18 UTC, rmarx requested changes

2024-01-29 10:18 UTC, rmarx commented on draft-ietf-quic-qlog-quic-events.md
> +The `ALPNIDentifier`` type supports either format.
```suggestion
The `ALPNIdentifier`` type supports either format.
```

2024-01-29 10:18 UTC, rmarx commented on draft-ietf-quic-qlog-quic-events.md
> +  ? string: text
```suggestion
  ? byte_value: hexstring
  ? string_value: text
```

Not the biggest fan of having "string" or "bytes" directly, as these are sometimes reserved keywords in programming languages.

2024-01-29 10:18 UTC, rmarx commented on draft-ietf-quic-qlog-quic-events.md
> +The `ALPNIDentifier`` type supports either format.
```suggestion
The `ALPNIDentifier`` type supports either format. Implementations SHOULD log at least one format, but MAY log both or none.
```

2024-01-29 14:02 UTC, rmarx approved these changes

2024-02-05 09:50 UTC, marten-seemann approved these changes

2024-02-05 09:53 UTC, merged