Explain 64-bit I-JSON issues but don't embed that in CDDL
quicwg/qlog pull request #388
Opened 2024-02-05 12:44 UTC by LPardue

Alternative to #359.

I-JSON can mess with big numbers and we can't constrain the range.
We don't want to mandate bigint support on anyone. We don't want
to make non-JSON serializers/parsers have to worry about stringified
numbers - so modifying the CDDL directly seems off.

There's lots of ways that implementations can internally handle values,
we don't care much about that here. For interop, settle on allow JSON parsers
to write uint64 as strings if they want to. Make it clear that parsers
should expect that, unless they have some non-standard way of knowing.

Fixes #229

2024-02-05 14:49 UTC, rmarx requested changes
I can live with the high-level approach here, but think the prose needs a bit of work to be clearer about the intent (see suggestions).

2024-02-05 14:49 UTC, rmarx commented on draft-ietf-quic-qlog-main-schema.md
> +uint64 values using JSON strings. JSON parsers, therefore, SHOULD support
```suggestion
  uint64 values using JSON strings. qlog parsers, therefore, SHOULD support
```

Not entirely sure that covers the entire load, but `JSON parsers` is also not quite correct I'd say :)

2024-02-05 14:49 UTC, rmarx commented on draft-ietf-quic-qlog-main-schema.md
> +information indicating that neither the serializer or parser are constrained by
```suggestion
information indicating that neither the serializer nor parser are constrained by
```

2024-02-05 14:49 UTC, rmarx commented on draft-ietf-quic-qlog-main-schema.md
> +parsing of strings or numbers into uint64 unless there is out-of-band
```suggestion
parsing of uint64 values from JSON strings or JSON numbers unless there is out-of-band
```

2024-02-06 15:30 UTC, LPardue commented
those suggestions make it better, thanks

2024-02-19 08:58 UTC, rmarx approved these changes

2024-02-19 09:24 UTC, merged