Add fin and reset_stream fields
quicwg/qlog pull request #396
Opened 2024-02-19 05:15 UTC by LPardue

Fixes #375.

Per the discussion, it can be useful to know when an application triggers a
stream close, or when it receives one, without having to do offset/length maths.

I omitted stop_sending in this commit because it seems a little bit of a stretch,
mainly because it's wire image has no offset or final size. Also, STOP_SENDING
relates to asking the peer to do something, which further complicates the
(potential) use of offset and length fields.

An alternative would be to keep `fin` here but define new events for reset and
stop. Those could both contain from, to and error fields but only the reset
would have offset and length.

2024-02-19 09:33 UTC, rmarx commented
Discussed during editorial meeting:
Keep `fin` here, move `reset_stream` and `stop_sending` to separate event(s) (possibly having 2 because reset_stream is so different from stop_sending).

@marten-seemann it would help to have a quick mockup of what `reset_stream_at` might look like (not because we want to add it to main qlog yet, but if the current design would be compatible with that, it would be nice :)

2024-02-28 10:53 UTC, rmarx commented
Actually discussed further during meeting, opinions changed :) 

I'm now in favor of something quite general, say:

```
? additional_info: [+ text]

; possible values for QUIC/H3 currently are "fin_set", "stream_reset", "stream_reset_at", "stop_sending"
```

With the idea that other events can be used to determine what exactly happened (e.g., look at the actual STREAM_RESET frame) and keep this event what it was originally intended for: showing when which type of data (and now info) is communicated between the layers (as this doesn't always coincide with packet sent/received)

2024-06-27 18:41 UTC, rmarx requested changes
See latest comment (which I, again, didn't submit as an actual review apparently)

2024-06-28 13:15 UTC, LPardue commented
> See latest comment (which I, again, didn't submit as an actual review apparently)

Do you mean this one https://github.com/quicwg/qlog/pull/396#issuecomment-1968725064, or something else?

2024-06-28 13:17 UTC, rmarx commented
that one indeed :) sorry for the confusion

2024-06-28 13:24 UTC, LPardue commented
Reading between the lines, I think we don't want a `text` type but extendable socket-mabobs. Lemme give that a crack.

2024-07-03 12:59 UTC, rmarx approved these changes

2024-07-03 13:20 UTC, merged